linters-settings:
  errcheck:
    check-type-assertions: true
  exhaustive:
    check-generated: false
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false
    default-signifies-exhaustive: true
    package-scope-only: false
  gocognit:
    min-complexity: 30
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gocyclo:
    min-complexity: 30
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - exhaustruct
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

run:
  issues-exit-code: 1